### ISSUE TITLE
一些引脚问题

### ISSUE THREAD

**Issue by ErrorChen** [Air-duino/Arduino-Air001-Drivers#3]
1.Datasheet上写有一个12位ADC，请问是analogRead的精度设为12位吗？然后有几个引脚可以调用DAC？
2.请问下PWM输出精度有几位？是只有默认的8位还是有更高？然后PWM输出频率范围是多少，调到最高的话，会对芯片运行有什么影响？
3.air001是否还有除001以外的USRT口。包含Serial0在内的USRT引脚，上传程序的时候是否需要断开除下载器外的其它链接
4.air001所链接的下载器，除GND和VCC外，是否有可以精简的口？比如留下GND，VCC，TX，RX。
5.air001如果想持续查看串口，是要一直插着下载器吗？还是有其它方法？
  期待您的早日回复，谢谢

**Comment by HalfSweet** [comment]
link https://github.com/Air-duino/Arduino-AirMCU/issues/77
